### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by gthb1** [Plisio/whmcs-plugin#2]
whmcs-plugin-1.0.3.zip\whmcs-plugin-1.0.3\modules\gateways\Plisio\version.php
contains version 1.0.2
is that intended?

**Comment by timurwcd** [comment]
Thx. Fixed

**Comment by gthb1** [comment]
If you download the latest (1.0.3) release, it is 1.0.2.
If you download the master, it is 1.0.3.
Generally great work!!!
